### ISSUE TITLE
Problem: vim-grammarous no longer works on 7.4.x

### ISSUE THREAD

**Issue by sappo** [rhysd/vim-grammarous#33]
When I run vim-grammarous on vim 7.4.x it starts with the following message:
```
Grammar check has started with job(process 22703 run)...
```
and after spell checking finished it comes back with the following error:
```
Error detected while processing function <SNR>221_on_check_done_vim8:
line    2:
E118: Too many arguments for function: ch_status
E15: Invalid expression: ch_status(a:channel, {'part' : 'out'}) ==# 'buffered'
```

**Comment by rhysd** [comment]
thank you for report.

hmm... early job implementation in Vim7.4 may be not available. I didn't confirm that. 7.4 might fallback into blocking command execution.

**Comment by rhysd** [comment]
It seems that 8.0.27 is required. I fixed it in 74a88d2

**Comment by sappo** [comment]
Thanks

Am 24.02.2017 1:03 vorm. schrieb "Linda_pp" <notifications@github.com>:

It seems that 8.0.27 is required. I fixed it in 74a88d2
<https://github.com/rhysd/vim-grammarous/commit/74a88d233056ac63ef65b3dd6766494ec33e6f2e>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rhysd/vim-grammarous/issues/33#issuecomment-282162273>,
or mute the thread
